springfox:
  documentation:
    swagger:  
      v2:
        path: /api-docs
        
server:
  contextPath: /salud/mscmd-unidades1n/v1 
  port: ${port}
  #port: 9070
  
spring:
  jackson:
    date-format: mx.gob.imss.cit.api.unidades1n.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    mongodb:
      host: 172.16.164.15
      port: 27017
      database: UNIDAD_MEDICA

  application:
    name: mscmd-unidades1n
  
  profiles:
    active: "${activatedProperties}" 
    
eureka:
  client:
    serviceUrl: 
      defaultZone: http://172.16.168.80:7001/eureka/, http://172.16.168.80:7002/eureka/

