springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs       

server:
  contextPath: /salud/msomt-orientacion/v1  
  port: ${port}
  
spring:
  jackson:
    date-format: mx.gob.imss.cit.api.omt.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: msomt-orientacion
  profiles:
    active: "${activatedProperties}" 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.168.80:7001/eureka/, http://172.16.168.80:7002/eureka/

##ENDOPOINTS MS OMT
#ENDPOINT_VIGENCIA: "${uri_vigencia}"
#ENDPOINT_UNIDADES: "${uri_unidades}"
ENDPOINT_VIGENCIA: http://172.16.168.73:9003/salud/msomt-vigencia/v1/vigencia/ 
ENDPOINT_UNIDADES: http://172.16.168.73:9001/salud/mscmd-unidades1n/v1/unidades/ 



##########- TIME OUT CONEXION EN MILISEGUNDOS -##########
URI_VIGENCIA_TIMEOUTCONNECTION: 5000
URI_VIGENCIA_TIMEOUTREADER: 5000
URI_UNIDAD_TIMEOUTCONNECTION: 4000
URI_UNIDAD_TIMEOUTREADER: 2000


