springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  contextPath: /salud/msomt-vigencia/v1
  port: ${port}  
  #  port: 7061
  
spring:
  jackson:
    date-format: mx.gob.imss.cit.api.vigencia.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  application:
    name: msomt-vigencia
    
  profiles:
    active: "${activatedProperties}" 
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.168.80:7001/eureka/, http://172.16.168.80:7002/eureka/
 
